# Tab navigation

keybind = alt+left=previous_tab

keybind = alt+right=next_tab



# Clipboard operations

#keybind = ctrl+c=copy_to_clipboard

keybind = ctrl+v=paste_from_clipboard



# clear

keybind = ctrl+l=reset

#keybind = ctrl+a=crash



# Other useful bindings

keybind = ctrl+t=new_tab

keybind = ctrl+w=close_surface
