# Put in ~/.config/starship.toml

add_newline = false

[line_break]
disabled = false

[character]
vicmd_symbol = "[█](bold yellow)"

[kubernetes]
disabled = false
format = '[\[k8s: $context\($namespace\)\]](bold blue) '
