# Put in ~/.config/starship.toml

add_newline = false

[line_break]
disabled = false

[character]
success_symbol = "[⩥](bold green)"
error_symbol = "[⩥](bold gray)"
vicmd_symbol = "[▣](bold 208)"

[kubernetes]
disabled = false
format = '[\[k8s: $context\($namespace\)\]](bold blue) '
